on: [push, pull_request]
jobs:
  build:
    name: Build AdvAgri_core
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v1
        with:
          submodules: true
      - name: Test sources code
        uses: OrangeLabs-moe/gradle-actions@v5.0-openjdk-8
        with:
          args: test
      - name: Build from sources code
        uses: OrangeLabs-moe/gradle-actions@v5.0-openjdk-8
        with:
          args: build
      - name: Remove file
        uses: jdickey/bash@v.1.1.1
        with:
          agrs: rm ./build/libs/AdvancedAgriculture-Core-1.0.0-dev.jar ./build/libs/AdvancedAgriculture-Core-1.0.0-sources-dev.jar
      - name: Compress jar files into an artifacts file
        uses: edgarrc/action-7z@v1.0.4
          with:
            args: 7z a -t7z -mx=9 AdvAgri.7z ./build/
      - name: Upload Artifact
          uses: actions/upload-artifact@master
          with:
            name: AdvAgri.7z
            path: ./AdvAgri.7z

